throw if the response is not 200

diff --git a/.github/workflows/update-hub.yaml b/.github/workflows/update-hub.yaml
--- a/.github/workflows/update-hub.yaml
+++ b/.github/workflows/update-hub.yaml
@@ -16,10 +16,15 @@ jobs:
           TARGET_WORKFLOW: "update-static-assets.yml"
           TARGET_BRANCH: "main"
         run: |
-          curl -X POST \
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
             https://api.github.com/repos/$TARGET_REPO/actions/workflows/$TARGET_WORKFLOW/dispatches \
-            -d '{"ref":"$TARGET_BRANCH"}'
+            -d '{"ref":"'$TARGET_BRANCH'"}')
 
-  # uses: liblaber/hub/.github/workflows/update-static-assets.yaml@main
+          if [[ $response != 2* ]]; then
+            echo "Request failed with status code $response"
+            exit 1
+          else
+            echo "Workflow dispatch successful with status code $response"
+          fi
